name: demo.playwright
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
jobs:
  todomvcTests:
    name: "todomvc tests"
    runs-on: buildjet-4vcpu-ubuntu-2004
    container: mcr.microsoft.com/playwright:focal
    env:
      TESTGROUP: todomvc
      BASEURL: https://demo.playwright.dev/todomvc # Playwright tests use this for baseURL
    environment:
      name: todomvc
      url: https://testresults.marcusfelling.com/${{ env.TESTGROUP }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: |
          npm i

      - name: Run ${{ env.TESTGROUP }} Tests
        continue-on-error: false
        working-directory: ${{ env.TESTGROUP }}
        run: PLAYWRIGHT_DASHBOARD_KEY=${{SECRET_INGESTION_KEY}} npx playwright test --reporter playwright-dashboard
          # HOME=/root npx playwright test